begin;

create table if not exists public.fields (
    id integer primary key,
    name text not null unique
);

create table if not exists public.daily_plan (
    plan_date date not null,
    field_id integer not null references public.fields(id),
    position integer not null,
    primary key (plan_date, field_id),
    unique (plan_date, position)
);

create table if not exists public.plan_days (
    plan_date date primary key,
    initialized boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.harvests (
    id bigint generated by default as identity primary key,
    harvest_date date not null,
    field_id integer not null references public.fields(id),
    interval_days integer not null check (interval_days >= 0),
    a numeric(12,2) not null default 0 check (a >= 0),
    b numeric(12,2) not null default 0 check (b >= 0),
    c numeric(12,2) not null default 0 check (c >= 0),
    xl numeric(12,2) not null default 0 check (xl >= 0),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (harvest_date, field_id)
);

insert into public.fields (id, name)
select i, 'Põld ' || i
from generate_series(1, 14) as i
on conflict (id) do update set name = excluded.name;

create or replace function public.get_field_interval(
    p_target_date date,
    p_field_id integer
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
    v_last_date date;
    v_position integer;
begin
    select max(harvest_date)
    into v_last_date
    from public.harvests
    where field_id = p_field_id
      and harvest_date < p_target_date;

    if v_last_date is not null then
        return greatest(0, p_target_date - v_last_date);
    end if;

    select position
    into v_position
    from public.daily_plan
    where plan_date = p_target_date
      and field_id = p_field_id;

    if v_position is null then
        return 5;
    end if;

    return case ((v_position - 1) % 3)
        when 0 then 5
        when 1 then 5
        else 4
    end;
end;
$$;

create or replace function public.ensure_default_daily_plan(
    p_plan_date date
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    if exists (
        select 1 from public.plan_days where plan_date = p_plan_date
    ) then
        return;
    end if;

    insert into public.plan_days(plan_date)
    values (p_plan_date)
    on conflict do nothing;

    insert into public.daily_plan(plan_date, field_id, position)
    select
        p_plan_date,
        ranked.id,
        row_number() over (
            order by ranked.last_harvest nulls first, ranked.id
        )
    from (
        select
            f.id,
            max(h.harvest_date) as last_harvest
        from public.fields f
        left join public.harvests h on h.field_id = f.id
        group by f.id
    ) ranked
    order by ranked.last_harvest nulls first, ranked.id
    limit 3;
end;
$$;

create or replace function public.get_daily_plan(
    p_plan_date date
)
returns table (
    field_id integer,
    field_name text,
    position integer,
    interval_days integer
)
language sql
security definer
set search_path = public
as $$
    select
        p.field_id,
        f.name as field_name,
        p.position,
        public.get_field_interval(p.plan_date, p.field_id) as interval_days
    from public.daily_plan p
    join public.fields f on f.id = p.field_id
    where p.plan_date = p_plan_date
    order by p.position;
$$;

create or replace function public.add_daily_plan_field(
    p_plan_date date,
    p_field_id integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_position integer;
begin
    insert into public.plan_days(plan_date)
    values (p_plan_date)
    on conflict do nothing;

    select coalesce(max(position), 0) + 1
    into v_position
    from public.daily_plan
    where plan_date = p_plan_date;

    insert into public.daily_plan(plan_date, field_id, position)
    values (p_plan_date, p_field_id, v_position)
    on conflict (plan_date, field_id) do nothing;
end;
$$;

create or replace function public.remove_daily_plan_field(
    p_plan_date date,
    p_field_id integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.plan_days(plan_date)
    values (p_plan_date)
    on conflict do nothing;

    delete from public.daily_plan
    where plan_date = p_plan_date
      and field_id = p_field_id;

    with reordered as (
        select
            field_id,
            row_number() over (order by position, field_id) as new_position
        from public.daily_plan
        where plan_date = p_plan_date
    )
    update public.daily_plan p
    set position = r.new_position
    from reordered r
    where p.plan_date = p_plan_date
      and p.field_id = r.field_id;
end;
$$;

create or replace function public.get_harvest_history(
    p_limit integer default 300
)
returns table (
    harvest_date date,
    field_name text,
    interval_days integer,
    a numeric,
    b numeric,
    c numeric,
    xl numeric,
    total numeric
)
language sql
security definer
set search_path = public
as $$
    select
        h.harvest_date,
        f.name as field_name,
        h.interval_days,
        h.a,
        h.b,
        h.c,
        h.xl,
        (h.a + h.b + h.c + h.xl) as total
    from public.harvests h
    join public.fields f on f.id = h.field_id
    order by h.harvest_date desc, h.field_id
    limit greatest(1, least(p_limit, 2000));
$$;



create table if not exists public.weather_daily (
    weather_date date primary key,
    source_station text not null default 'Häädemeeste',

    temp_avg_c numeric(6,2),
    temp_min_c numeric(6,2),
    temp_max_c numeric(6,2),
    humidity_avg_pct numeric(6,2) check (humidity_avg_pct between 0 and 100),
    humidity_min_pct numeric(6,2) check (humidity_min_pct between 0 and 100),
    humidity_max_pct numeric(6,2) check (humidity_max_pct between 0 and 100),
    precipitation_mm numeric(10,2) check (precipitation_mm >= 0),

    wind_avg_ms numeric(7,2) check (wind_avg_ms >= 0),
    wind_max_ms numeric(7,2) check (wind_max_ms >= 0),
    wind_gust_ms numeric(7,2) check (wind_gust_ms >= 0),
    wind_direction_deg numeric(6,2) check (wind_direction_deg >= 0 and wind_direction_deg <= 360),

    pressure_avg_hpa numeric(8,2),
    dewpoint_avg_c numeric(6,2),
    sunshine_hours numeric(6,2) check (sunshine_hours >= 0),

    radiation_mj_m2 numeric(10,2) check (radiation_mj_m2 >= 0),
    radiation_station text not null default 'Pärnu',

    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create or replace function public.get_weather_status(
    p_weather_date date
)
returns table (
    weather_date date,
    is_complete boolean,
    missing_fields text[]
)
language sql
security definer
set search_path = public
as $$
    select
        p_weather_date,
        (
            w.temp_avg_c is not null
            and w.temp_min_c is not null
            and w.temp_max_c is not null
            and w.humidity_avg_pct is not null
            and w.precipitation_mm is not null
            and w.wind_avg_ms is not null
            and w.wind_gust_ms is not null
            and w.radiation_mj_m2 is not null
        ) as is_complete,
        array_remove(array[
            case when w.temp_avg_c is null then 'Keskmine temperatuur' end,
            case when w.temp_min_c is null then 'Miinimumtemperatuur' end,
            case when w.temp_max_c is null then 'Maksimumtemperatuur' end,
            case when w.humidity_avg_pct is null then 'Keskmine õhuniiskus' end,
            case when w.precipitation_mm is null then 'Sademed' end,
            case when w.wind_avg_ms is null then 'Keskmine tuulekiirus' end,
            case when w.wind_gust_ms is null then 'Maksimaalne puhang' end,
            case when w.radiation_mj_m2 is null then 'Globaalradiatsioon' end
        ], null) as missing_fields
    from (select 1) seed
    left join public.weather_daily w on w.weather_date = p_weather_date;
$$;

alter table public.fields enable row level security;
alter table public.daily_plan enable row level security;
alter table public.plan_days enable row level security;
alter table public.harvests enable row level security;
alter table public.weather_daily enable row level security;

revoke all on public.fields from anon, authenticated;
revoke all on public.daily_plan from anon, authenticated;
revoke all on public.plan_days from anon, authenticated;
revoke all on public.harvests from anon, authenticated;

grant execute on function public.get_field_interval(date, integer) to service_role;
grant execute on function public.ensure_default_daily_plan(date) to service_role;
grant execute on function public.get_daily_plan(date) to service_role;
grant execute on function public.add_daily_plan_field(date, integer) to service_role;
grant execute on function public.remove_daily_plan_field(date, integer) to service_role;
grant execute on function public.get_harvest_history(integer) to service_role;

commit;
